### ISSUE TITLE
OL8 - Latest UEK kernel (5.15.0-105.125.6.2.1.el8uek) brakes Fibrechannel qla2xxx driver and Networking on OLVM nodes.

### ISSUE THREAD

**Issue by morgancoxuk** [oracle/linux-uek#19]
Hi,

I have for the last few days been troubleshooting issues with multiple OL8  servers - all OLVM nodes.

It looks like the latest UEK 5.15.x kernel breaks the nodes in multiple ways - I have created 2 forum posts regarding this with details

qla2xxx (fc) : https://forums.oracle.com/ords/apexds/post/olvm-ol8-warning-lastest-5-15-uek-kernel-breaks-fibre-chann-0376

OLVM network issues on bonded interfaces : https://forums.oracle.com/ords/apexds/post/olvm-ol8-x-help-some-nodes-we-cannot-do-any-network-changes-6280 

Both these issues went away by either installing the 4.18.x kernel or an older 5.15 UEK kernel. I have seen the network issues  on all OL8 node servers updates updated within the last 2 weeks, and the fc issue only on the latest uek kernel.

**Comment by scoter-oracle** [comment]
I provided my feedback on the Oracle forum website. Please, keep the two issues divided to avoid confusion on the same.
I'm going to close this issue here, due to two main reasons:

1. reporting two problem on the same GitHub issue is not going to work well
2. I'm following-up on the forum.oracle.com threads you've opened

Thanks!

**Comment by almaclang** [comment]
That's great. Thanks, Sergio.
